---
- import_playbook: create_vpc.yaml
- import_playbook: create_acl.yaml
- import_playbook: create_sg.yaml
- import_playbook: create_rds.yaml
- import_playbook: create_asg.yaml
- import_playbook: provision_db.yaml
