---
- hosts: localhost
  gather_facts: no
  module_defaults:
    group/aws:
      profile: auburn
      region: "us-east-1"
  tasks:

    - name: Create Image Gallery
      postgresql_db:
        login_host: "{{ rds_info2.instance.endpoint }}"
        login_user: postgres
        login_password: PassMe12#$
        db: image_gallery
        state: present

    - name: Create Users
      postgresql_query:
        db: image_gallery
        login_host: "{{ rds_info2.instance.endpoint }}"
        login_user: postgres
        login_password: PassMe12#$
        query: CREATE USER image_gallery LOGIN PASSWORD simple

    - name: Create Users Table
      postgresql_query:
        db: image_gallery
        login_host: "{{ rds_info2.instance.endpoint }}"
        login_user: image_gallery
        login_password: simple
        query: CREATE TABLE users IF NOT EXISTS ( username varchar(200) PRIMARY KEY, password varchar(200), full_name varchar(200));
